name: Print Hello

on:
  push:
    branches:
      - main
    workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  

    - name: Run JavaScript code
      run: node hello.js
      id: hello_output
      continue-on-error: true

    - name: Echo Hello Output
      if: ${{ success() }}
      run: echo "Output: ${{ steps.hello_output.outputs.stdout }}"