name: Print Hello

# Specify the event that triggers the workflow (push to main branch and manual workflow dispatch)
on:
  push:
    branches:
      - main
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Run the JavaScript code and capture the output
      - name: Run JavaScript code
        run: node hello.js
        env:
          MY_SECRET: ${{ vars.SOME_URL }}
          SOME_URL : ${{ vars.SOME_URL }}
